# Taguchi Array

In [1]:
import numpy as np
from utils import validate_parameters

In [12]:
MODULE = 0.8e-3
MC = 0.8467e-3

In [ ]:
# Input array
z_s = [18, 16, 14] # sh * 2 = s
z_p2 = [31, 30, 33]
z_r2 = [83, 82, 80]
x_s = [0.3, 0.6, 0.7]
x_p1 = [0.6, 0.9, 1.0]
x_p2 = [-0.4, -0.3, -0.5]
x_r2 = [0.4, 0.5, 0.3]
gear_thickness = [6, 8, 12]

param_vals = [z_s, z_p2, z_r2, x_s, x_p1, x_p2, x_r2, gear_thickness]

paper_vals = [12, 32, 81, .476, .762, .536, 1.21, 10] # NOTE - 6 = 12 (z_s) / 2.

for i in range(len(param_vals)):
    # append paper_val to the front of the list
    param_vals[i].insert(0, paper_vals[i])

# Display the taguchi array in a table format with aligned columns
cols = ['z_s', 'z_p2', 'z_r2', 'x_s', 'x_p1', 'x_p2', 'x_r2', 'gear_thickness']
UPDATE_cols = ['z_s', 'z_r2', 'c_1', 'c_2', 'x_s', 'x_r2', 'gear_thickness']
new_cols = cols.copy()
new_cols[0] = "z_s/z_p1"
col_widths_new = []
for k, col in enumerate(new_cols):
    max_width = len(col)
    for i in range(len(param_vals[0])):
        if k == 0:
            val = f"{param_vals[0][i]} / {(90 - param_vals[0][i]) / 2}"
        else:
            val = param_vals[k][i]
        max_width = max(max_width, len(str(val)))
    col_widths_new.append(max_width + 2)
header_new = " | ".join(new_cols[k].center(col_widths_new[k]) for k in range(len(new_cols)))
separator_new = "-+-".join("-" * col_widths_new[k] for k in range(len(new_cols)))
print(header_new)
print(separator_new)
for i in range(len(param_vals[0])):
    row_values = []
    for k in range(len(new_cols)):
        if k == 0:
            value = f"{param_vals[0][i]} / {int((90 - param_vals[0][i]) / 2)}"
        else:
            value = param_vals[k][i]
        row_values.append(str(value).center(col_widths_new[k]))
    print(" | ".join(row_values))
print(separator_new)

  z_s/z_p1  |  z_p2  |  z_r2  |   x_s   |   x_p1  |   x_p2  |  x_r2  |  gear_thickness 
------------+--------+--------+---------+---------+---------+--------+-----------------
  12 / 39   |   32   |   81   |  0.476  |  0.762  |  0.536  |  1.21  |        10       
  18 / 36   |   31   |   83   |   0.3   |   0.6   |   -0.4  |  0.4   |        6        
  16 / 37   |   30   |   82   |   0.6   |   0.9   |   -0.3  |  0.5   |        8        
  14 / 38   |   33   |   80   |   0.7   |   1.0   |   -0.5  |  0.3   |        12       
------------+--------+--------+---------+---------+---------+--------+-----------------


In [3]:
Taguchi = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
[1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
[1, 1, 3, 3, 3, 3, 3, 3, 3, 3],
[1, 1, 4, 4, 4, 4, 4, 4, 4, 4],
[1, 2, 1, 1, 2, 2, 3, 3, 4, 4],
[1, 2, 2, 2, 1, 1, 4, 4, 3, 3],
[1, 2, 3, 3, 4, 4, 1, 1, 2, 2],
[1, 2, 4, 4, 3, 3, 2, 2, 1, 1],
[1, 3, 1, 2, 3, 4, 1, 2, 3, 4],
[1, 3, 2, 1, 4, 3, 2, 1, 4, 3],
[1, 3, 3, 4, 1, 2, 3, 4, 1, 2],
[1, 3, 4, 3, 2, 1, 4, 3, 2, 1],
[1, 4, 1, 2, 4, 3, 3, 4, 2, 1],
[1, 4, 2, 1, 3, 4, 4, 3, 1, 2],
[1, 4, 3, 4, 2, 1, 1, 2, 4, 3],
[1, 4, 4, 3, 1, 2, 2, 1, 3, 4],
[2, 1, 1, 4, 1, 4, 2, 3, 2, 3],
[2, 1, 2, 3, 2, 3, 1, 4, 1, 4],
[2, 1, 3, 2, 3, 2, 4, 1, 4, 1],
[2, 1, 4, 1, 4, 1, 3, 2, 3, 2],
[2, 2, 1, 4, 2, 3, 4, 1, 3, 2],
[2, 2, 2, 3, 1, 4, 3, 2, 4, 1],
[2, 2, 3, 2, 4, 1, 2, 3, 1, 4],
[2, 2, 4, 1, 3, 2, 1, 4, 2, 3],
[2, 3, 1, 3, 3, 1, 2, 4, 4, 2],
[2, 3, 2, 4, 4, 2, 1, 3, 3, 1],
[2, 3, 3, 1, 1, 3, 4, 2, 2, 4],
[2, 3, 4, 2, 2, 4, 3, 1, 1, 3],
[2, 4, 1, 3, 4, 2, 4, 2, 1, 3],
[2, 4, 2, 4, 3, 1, 3, 1, 2, 4],
[2, 4, 3, 1, 2, 4, 2, 4, 3, 1],
[2, 4, 4, 2, 1, 3, 1, 3, 4, 2],
])-1

In [4]:
first_set = []
Tag_vals = Taguchi[0][1:-1]
print(Tag_vals)
for i in range(len(param_vals)):
    first_set.append(param_vals[i][Tag_vals[i]])

[0 0 0 0 0 0 0 0]


In [5]:
first_set

[12, 32, 81, 0.476, 0.762, 0.536, 1.21, 10]

In [6]:
targ_set = 2 # 1-32
new_set = []
Tag_vals = Taguchi[targ_set-1][1:-1]
# print(Tag_vals)
for i in range(len(param_vals)):
    new_set.append(param_vals[i][Tag_vals[i]])
new_set

[12, 31, 83, 0.3, 0.6, -0.4, 0.4, 6]

In [7]:
set_list = []
for targ_set in range(len(Taguchi)):
    new_set = []
    Tag_vals = Taguchi[targ_set][1:-1]
    # print(Tag_vals)
    for i in range(len(param_vals)):
        new_set.append(param_vals[i][Tag_vals[i]])
    
    # Print the new set of parameters
    print(f"Set {targ_set + 1}: {new_set}")
    set_list.append(new_set)
    
    # Here you can add code to perform calculations or simulations with new_set if needed

Set 1: [12, 32, 81, 0.476, 0.762, 0.536, 1.21, 10]
Set 2: [12, 31, 83, 0.3, 0.6, -0.4, 0.4, 6]
Set 3: [12, 30, 82, 0.6, 0.9, -0.3, 0.5, 8]
Set 4: [12, 33, 80, 0.7, 1.0, -0.5, 0.3, 12]
Set 5: [18, 32, 81, 0.3, 0.6, -0.3, 0.5, 12]
Set 6: [18, 31, 83, 0.476, 0.762, -0.5, 0.3, 8]
Set 7: [18, 30, 82, 0.7, 1.0, 0.536, 1.21, 6]
Set 8: [18, 33, 80, 0.6, 0.9, -0.4, 0.4, 10]
Set 9: [16, 32, 83, 0.6, 1.0, 0.536, 0.4, 8]
Set 10: [16, 31, 81, 0.7, 0.9, -0.4, 1.21, 12]
Set 11: [16, 30, 80, 0.476, 0.6, -0.3, 0.3, 10]
Set 12: [16, 33, 82, 0.3, 0.762, -0.5, 0.5, 6]
Set 13: [14, 32, 83, 0.7, 0.9, -0.3, 0.3, 6]
Set 14: [14, 31, 81, 0.6, 1.0, -0.5, 0.5, 10]
Set 15: [14, 30, 80, 0.3, 0.762, 0.536, 0.4, 12]
Set 16: [14, 33, 82, 0.476, 0.6, -0.4, 1.21, 8]
Set 17: [12, 32, 80, 0.476, 1.0, -0.4, 0.5, 6]
Set 18: [12, 31, 82, 0.3, 0.9, 0.536, 0.3, 10]
Set 19: [12, 30, 83, 0.6, 0.6, -0.5, 1.21, 12]
Set 20: [12, 33, 81, 0.7, 0.762, -0.3, 0.4, 8]
Set 21: [18, 32, 80, 0.3, 0.9, -0.5, 1.21, 8]
Set 22: [18, 31, 82, 0.

In [8]:
in_val_sets = np.array(set_list)
in_val_sets[:, 0] = in_val_sets[:, 0] / 2 # divide by 2 to get z_sh

In [9]:
validate_parameters(in_val_sets[0][:-1])

[-0.1785147]
Total combinations: 1, Valid combinations: 1, Stage 2 constraint: 1


(array([6.]),
 array([39.]),
 array([32.]),
 array([81.]),
 array([0.476]),
 array([0.762]),
 array([0.536]),
 array([1.21]),
 array([7.5]),
 array([0.91168091]),
 array([0.01039048]),
 array([96.24193548]))

In [ ]:
this_set = in_val_sets[0]
ra = 0.5 * MODULE * ( this_set[0]*2 + 2*this_set[3] +  

In [10]:
validations = []
for i in range(len(in_val_sets)):
    validations.append(np.is_empty(validate_parameters(in_val_sets[i][:-1])))

AttributeError: module 'numpy' has no attribute 'is_empty'

In [ ]:
validations

[]